# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: PerformanceCenterTesting@1
  inputs:
    varPCServer: 'https://elr.deloitteresources.com/Loadtest/pcx/login?ReturnUrl=%2FLoadtest'
    varUserName: 'byasodakumar'
    varPassWord: 'satyA5308VSKP'
    varDomain: 'LA_County'
    varProject: 'LA_County'
    varTestID: '232'
    varAutoTestInstance: 'false'
    varTestInstID: '11'
    varTimeslotDuration: '30'
    artifactsDirectory: '$(Build.ArtifactStagingDirectory)/LRETest'

